### ISSUE TITLE
gopacket SIGSEGV

### ISSUE THREAD

**Issue by BinaryScary** [BinaryScary/GoScan#1]
https://github.com/BinaryScary/goscan/blob/c487cebbb6b173b4f1e6dcdd8d26bd88bea8bef7/goscan.go#L50

```
goroutine 1 [running]:
github.com/BinaryScary/goscan.NewScanner(0x0, 0xc4200a4438, 0x1, 0x1, 0x92d280, 0xc4200ac5c0,
0x1f4, 0x12c, 0xc4200a4030, 0x0, ...)
        /home/ubuntu/go/src/github.com/BinaryScary/goscan/goscan.go:50 +0xfc
github.com/BinaryScary/goscan.SetupScanner(0x7ffdc903e86b, 0x11, 0xc4200a4438, 0x1, 0x1, 0x1f4, 0x12c, 0x0)
        /home/ubuntu/go/src/github.com/BinaryScary/goscan/goscan.go:332 +0x136
main.main()
        /home/ubuntu/go/src/github.com/BinaryScary/sslWho/main.go:306 +0x532
```

**Comment by BinaryScary** [comment]
6e80063c1b9650800f12e36eb497f6f0b363cd1c Should fix this issue, if it persists investigate https://github.com/BinaryScary/goscan/blob/482bbfcd8b35501d395de594ffd2a4b0de27e8ba/goscan.go#L38, and add checks for nil pointer ip
